<?php
session_start();
require_once __DIR__ . '/../../vendor/autoload.php';
include_once(__DIR__ . '/../config/database.php');

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Only admin should generate reports
if (!isset($_SESSION['userID']) || ($_SESSION['user_type'] ?? '') !== 'admin') {
    http_response_code(403);
    echo 'Forbidden';
    exit;
}

$school_year = isset($_GET['school_year']) && is_numeric($_GET['school_year']) ? intval($_GET['school_year']) : null;

// Fetch school years
$syRes = $conn->query("SELECT id, year, semester FROM school_years ORDER BY year DESC, semester");
$schoolYears = [];
if ($syRes) {
    while ($r = $syRes->fetch_assoc()) $schoolYears[] = $r;
}

$spreadsheet = new Spreadsheet();
$spreadsheet->getProperties()->setCreator('Faculty Evaluation System')->setTitle('Evaluation Summary Report');

// Cover sheet with metadata
$cover = $spreadsheet->getActiveSheet();
$cover->setTitle('Cover');
$cover->setCellValue('A1', 'Faculty Evaluation System - Summary Report');
$cover->mergeCells('A1:E1');
$cover->setCellValue('A3', 'Generated At:');
$cover->setCellValue('B3', date('F j, Y \a\t g:i A'));
$cover->setCellValue('A4', 'Generated By:');
$cover->setCellValue('B4', $_SESSION['firstname'] . ' ' . ($_SESSION['lastname'] ?? $_SESSION['username'] ?? 'Admin'));
$cover->setCellValue('A6', 'Included School Year Filter:');
// Make school year filter human-readable (e.g., '2025-2026 - First Semester')
$schoolYearDisplay = 'All';
if ($school_year) {
    // try to find the school year record from the previously fetched list
    foreach ($schoolYears as $sy) {
        if ((int)$sy['id'] === (int)$school_year) {
            $sem = (string)$sy['semester'];
            if ($sem === '1' || stripos($sem, 'first') !== false) $semLabel = 'First Semester';
            elseif ($sem === '2' || stripos($sem, 'second') !== false) $semLabel = 'Second Semester';
            else $semLabel = $sy['semester'];
            $schoolYearDisplay = $sy['year'] . ' - ' . $semLabel;
            break;
        }
    }
    // fallback to the raw id if not found
    if ($schoolYearDisplay === 'All') $schoolYearDisplay = $school_year;
}
$cover->setCellValue('B6', $schoolYearDisplay);

// Overview sheet
$sheet = $spreadsheet->createSheet();
$sheet->setTitle('Overview');
$sheet->fromArray([
    'School Year',
    'Semester',
    'Total Evaluations',
    'Total Students',
    'Total Teachers',
    'Students Submitted (distinct)',
    'Teachers Submitted (distinct)',
    'Teachers Received Evaluations (distinct)',
    'Student Participation (%)',
    'Teacher Participation (%)'
], NULL, 'A1');
$row = 2;

foreach ($schoolYears as $sy) {
    if ($school_year && $school_year !== (int)$sy['id']) continue;
    $syId = (int)$sy['id'];

    // total evaluations
    $res = $conn->query("SELECT COUNT(*) AS cnt FROM evaluations WHERE school_year_id = " . $syId);
    $total = $res ? (int)$res->fetch_assoc()['cnt'] : 0;

    // total students and teachers (global counts from users table)
    $resTotalStudents = $conn->query("SELECT COUNT(*) AS cnt FROM users WHERE user_type = 'student'");
    $totalStudents = $resTotalStudents ? (int)$resTotalStudents->fetch_assoc()['cnt'] : 0;
    $resTotalTeachers = $conn->query("SELECT COUNT(*) AS cnt FROM users WHERE user_type = 'teacher'");
    $totalTeachers = $resTotalTeachers ? (int)$resTotalTeachers->fetch_assoc()['cnt'] : 0;

    // distinct student evaluators (students who submitted at least one evaluation)
    $res = $conn->query("SELECT COUNT(DISTINCT evaluator_id) AS cnt FROM evaluations WHERE school_year_id = " . $syId . " AND evaluator_type='student'");
    $studentsSubmitted = $res ? (int)$res->fetch_assoc()['cnt'] : 0;

    // distinct teacher evaluators (teachers who submitted evaluations)
    $res = $conn->query("SELECT COUNT(DISTINCT evaluator_id) AS cnt FROM evaluations WHERE school_year_id = " . $syId . " AND evaluator_type='teacher'");
    $teachersSubmitted = $res ? (int)$res->fetch_assoc()['cnt'] : 0;

    // distinct teachers who received at least one evaluation
    $res = $conn->query("SELECT COUNT(DISTINCT teacher_id) AS cnt FROM evaluations WHERE school_year_id = " . $syId . " AND teacher_id IS NOT NULL");
    $teachersReceived = $res ? (int)$res->fetch_assoc()['cnt'] : 0;

    // Participation rates
    $studentParticipation = $totalStudents > 0 ? round(($studentsSubmitted / $totalStudents) * 100, 2) : 0;
    $teacherParticipation = $totalTeachers > 0 ? round(($teachersSubmitted / $totalTeachers) * 100, 2) : 0;

    $sheet->setCellValue("A{$row}", $sy['year']);
    $sheet->setCellValue("B{$row}", $sy['semester']);
    $sheet->setCellValue("C{$row}", $total);
    $sheet->setCellValue("D{$row}", $totalStudents);
    $sheet->setCellValue("E{$row}", $totalTeachers);
    $sheet->setCellValue("F{$row}", $studentsSubmitted);
    $sheet->setCellValue("G{$row}", $teachersSubmitted);
    $sheet->setCellValue("H{$row}", $teachersReceived);
    $sheet->setCellValue("I{$row}", $studentParticipation);
    $sheet->setCellValue("J{$row}", $teacherParticipation);
    $row++;
}


// Set active sheet back to Overview
$spreadsheet->setActiveSheetIndexByName('Overview');



// Top Teachers sheet
$topSheet = $spreadsheet->createSheet();
$topSheet->setTitle('Top Teachers');
$topSheet->fromArray(['Rank', 'Teacher ID', 'Teacher Name', 'Avg Rating', 'Total Evaluations'], NULL, 'A1');
$tr = 2;
$tq = "SELECT e.teacher_id, CONCAT(u.firstname, ' ', u.lastname) AS teacher_name, ROUND(AVG(CAST(e.answer AS DECIMAL)),2) AS avg_rating, COUNT(e.id) AS cnt FROM evaluations e JOIN users u ON e.teacher_id = u.id";
if ($school_year) $tq .= " WHERE e.school_year_id = " . intval($school_year);
$tq .= " GROUP BY e.teacher_id ORDER BY avg_rating DESC, cnt DESC LIMIT 50";
$tres = $conn->query($tq);
if ($tres) {
    $rank = 1;
    while ($trow = $tres->fetch_assoc()) {
        $topSheet->setCellValue("A{$tr}", $rank);
        $topSheet->setCellValue("B{$tr}", $trow['teacher_id']);
        $topSheet->setCellValue("C{$tr}", $trow['teacher_name']);
        $topSheet->setCellValue("D{$tr}", $trow['avg_rating']);
        $topSheet->setCellValue("E{$tr}", $trow['cnt']);
        $tr++;
        $rank++;
    }
}

// Styling: bold headers, freeze panes, autosize

// Teacher by Criteria sheet (one column per criterion; averages per teacher)
$tcSheet = $spreadsheet->createSheet();
$tcSheet->setTitle('Teacher by Criteria');

// Fetch criteria that are used in evaluations for teachers
$critSql = "SELECT DISTINCT c.id, c.name FROM criteria c JOIN questionnaires q ON q.criteria_id = c.id JOIN evaluations e ON e.questionnaire_id = q.id WHERE e.teacher_id IS NOT NULL";
if ($school_year) $critSql .= " AND e.school_year_id = " . intval($school_year);
$critSql .= " ORDER BY c.name";
$critRes = $conn->query($critSql);
$criteria = [];
if ($critRes) {
    while ($cr = $critRes->fetch_assoc()) $criteria[] = $cr;
}

// Header row: Teacher ID, Teacher Name, <criteria...>, Avg All, No. of Res, Department
$headers = ['Teacher ID', 'Teacher Name'];
foreach ($criteria as $c) $headers[] = $c['name'];
$headers = array_merge($headers, ['Avg All', 'No. of Res', 'Department']);
$tcSheet->fromArray($headers, NULL, 'A1');

// Get aggregated averages per teacher per criterion
$aggSql = "SELECT e.teacher_id, c.id AS crit_id, ROUND(AVG(CAST(e.answer AS DECIMAL)),2) AS avg_answer, COUNT(e.id) AS cnt FROM evaluations e JOIN questionnaires q ON e.questionnaire_id = q.id JOIN criteria c ON q.criteria_id = c.id WHERE e.teacher_id IS NOT NULL";
if ($school_year) $aggSql .= " AND e.school_year_id = " . intval($school_year);
$aggSql .= " GROUP BY e.teacher_id, c.id";
$aggRes = $conn->query($aggSql);
$agg = [];
if ($aggRes) {
    while ($a = $aggRes->fetch_assoc()) {
        $tid = $a['teacher_id'];
        $cid = $a['crit_id'];
        $agg[$tid][$cid] = ['avg' => $a['avg_answer'], 'cnt' => $a['cnt']];
    }
}

// Get teacher list (include department if available)
$tq = "SELECT id, firstname, lastname";
// optionally include department if column exists
$colCheck = $conn->query("SHOW COLUMNS FROM users LIKE 'department'");
$hasDepartment = $colCheck && $colCheck->num_rows > 0;
if ($hasDepartment) $tq .= ", department";
$tq .= " FROM users WHERE user_type = 'teacher' ORDER BY lastname, firstname";
$tres = $conn->query($tq);
$tr = 2;
if ($tres) {
    while ($trow = $tres->fetch_assoc()) {
        $tid = $trow['id'];
        $tname = trim(($trow['firstname'] ?? '') . ' ' . ($trow['lastname'] ?? ''));
        $tcSheet->setCellValue("A{$tr}", $tid);
        $tcSheet->setCellValue("B{$tr}", $tname);

        // fill criteria columns
        $colIndex = 3; // C
        $respSum = 0;
        $weightedSum = 0.0;
        foreach ($criteria as $c) {
            $cid = $c['id'];
            if (isset($agg[$tid][$cid])) {
                $val = $agg[$tid][$cid]['avg'];
                $cnt = $agg[$tid][$cid]['cnt'];
                $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colIndex);
                $tcSheet->setCellValue($colLetter . $tr, $val);
                $respSum += $cnt;
                $weightedSum += ($val * $cnt);
            } else {
                $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colIndex);
                $tcSheet->setCellValue($colLetter . $tr, '');
            }
            $colIndex++;
        }

        // overall average (weighted) and total responses
        $overallAvg = $respSum > 0 ? round($weightedSum / $respSum, 2) : '';
        $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colIndex);
        $tcSheet->setCellValue($colLetter . $tr, $overallAvg); // Avg All
        $colLetter2 = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colIndex + 1);
        $tcSheet->setCellValue($colLetter2 . $tr, $respSum); // No. of Res
        if ($hasDepartment) {
            $colLetter3 = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colIndex + 2);
            $tcSheet->setCellValue($colLetter3 . $tr, $trow['department']);
        }

        $tr++;
    }
}

// Rotate criteria headers vertically and enable wrap
if (count($criteria) > 0) {
    // criteria headers start at column 3 (C) and go for count(criteria)
    $start = 3;
    $end = 2 + count($criteria);
    for ($ci = $start; $ci <= $end; $ci++) {
        $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci);
        $cell = "{$col}1";
        $tcSheet->getStyle($cell)->getAlignment()->setTextRotation(90);
        $tcSheet->getStyle($cell)->getAlignment()->setWrapText(true);
        $tcSheet->getColumnDimension($col)->setWidth(12);
    }
}

foreach ($spreadsheet->getAllSheets() as $s) {
    $s->getStyle('A1:Z1')->getFont()->setBold(true);
    $s->freezePane('A2');
    foreach (range('A', $s->getHighestColumn()) as $col) {
        $s->getColumnDimension($col)->setAutoSize(true);
    }
}

$writer = new Xlsx($spreadsheet);
// Build a readable filename: include school year (or 'all'), semester as text, and date like 'October_23_2025'
$syLabel = 'all';
$semesterLabel = '';
if ($school_year) {
    // find matching school year record
    foreach ($schoolYears as $s) {
        if ((int)$s['id'] === (int)$school_year) {
            $syLabel = str_replace(' ', '_', $s['year']);
            $sem = (string)$s['semester'];
            if ($sem === '1' || stripos($sem, 'first') !== false) $semesterLabel = 'First_Semester';
            elseif ($sem === '2' || stripos($sem, 'second') !== false) $semesterLabel = 'Second_Semester';
            else $semesterLabel = preg_replace('/\s+/', '_', $sem);
            break;
        }
    }
}
$dateLabel = date('F_j_Y'); // e.g., October_23_2025
$filenameParts = array_filter(['evaluation_summary', $syLabel, $semesterLabel, $dateLabel]);
$filename = implode('_', $filenameParts) . '.xlsx';

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: max-age=0');

$writer->save('php://output');
exit;
